### ISSUE TITLE
Bar disappears in a couple seconds and doesn't always appear

### ISSUE THREAD

**Issue by SmallSansSerif** [games647/mcMMOExtras#1]
I'm running Spigot 1.8.4 and can't seem to get the bar to display for very long or consistently.

**Comment by TuxCoding** [comment]
According to the barAPI comments, the boss bar (in 1.8 or above) only shows up if the player sees the dragon. It's difficult to place the dragon somewhere the player actually sees it directly. (Related to https://github.com/confuser/BarAPI/issues/48)

The orginal author implemented the feature that the bar will disappear after specifc time, but I could change it that the dragon follows the movements of the player and so stay shown.

**Comment by SmallSansSerif** [comment]
Would this create potential lag due to the use of the hidden Dragon?

**Comment by TuxCoding** [comment]
Dragons cannot be hidden in 1.8, but yes it would take some performance effects if the dragon has to follow the player in order to keep the boss bar show up. 

As far as I know this behaviour isn't intended and will be fixed in 1.9

**Comment by SmallSansSerif** [comment]
Ok thanks for the info.. I like the idea of using the bar for mcMMO skills but sounds like it's better to wait until 1.9

**Comment by TuxCoding** [comment]
Alright, then I close this.
