### ISSUE TITLE
Default Permissions

### ISSUE THREAD

**Issue by Zefferis** [games647/mcMMOExtras#11]
I installed the plugin into my server (wonderful plugin), but I was testing and using the plugin as an OP.

Since we aren't running a permissions plugin we noticed the oddity in which default players are able to use the command /mcmmoextras to toggle the expbar, however they are unable to view the bar unless they are OP'd

Would there we be a way to switch those permissions such that default players cannot toggle the expbar (I assume it's a global setting?) but are able to view the expbar when it is active without an explicit permission to do so?

**Comment by TuxCoding** [comment]
I noticed that the command has no permission at all. I'm currently not at home, but later I'm going to add a permission for that and a default true value for both.

**Comment by Zefferis** [comment]
Sweet, thanks!
