### ISSUE TITLE
Purple color bar...

### ISSUE THREAD

**Issue by xFrah** [games647/mcMMOExtras#13]
if i set the language to italian the color of the bossbar becomes purple...

**Comment by xFrah** [comment]
i have the latest version of the plugin... you said that it was solved but it isn't

**Comment by TuxCoding** [comment]
I guess you have an invalid configuration file. Please post your server log.

**Comment by xFrah** [comment]
i have the default config... by the way i'll post the server log in a few hours

**Comment by TuxCoding** [comment]
>if i set the language to italian

What do you mean with language italien? There is no language selection in mcMMOExtras.

**Comment by xFrah** [comment]
the language selection on mcmmo... if i change that your plugin doesn't work anymore... if i change it back to english it works

**Comment by xFrah** [comment]
can i get an answer?

**Comment by TuxCoding** [comment]
Please be patient. Please wait at least some minutes. I'm currently setting up a development build instance. So you can get the newest versions from here: https://ci.codemc.org/job/Games647/job/mcMMOExtras/

**Comment by xFrah** [comment]
wow sorry i thought you closed the thread... i'm new on github

**Comment by TuxCoding** [comment]
Could you try the newest build please?

**Comment by xFrah** [comment]
i think you fixed the name of the skill... but not the bar color... do i have to delete config.yml?

**Comment by xFrah** [comment]
![cattaaaaaura](https://user-images.githubusercontent.com/37962249/38175603-5e9bd0a4-35df-11e8-9b78-3a73bb3ccf56.PNG)

**Comment by xFrah** [comment]
i changed the standard color to yellow instead of purple and segmented instead of solid to make it look better... that's my edit

**Comment by xFrah** [comment]
my only edit

**Comment by TuxCoding** [comment]
Well looks like I fixed it for bar.color, but not for segements and barColor

**Comment by TuxCoding** [comment]
Please try the next build that includes the referenced commit.

**Comment by xFrah** [comment]
it works perfectly now! Thanks! i'll add a positive feedback
