### ISSUE TITLE
Any way to display bar but hide the boss?

### ISSUE THREAD

**Issue by mibby** [games647/mcMMOExtras#3]
Is there any way to display the boss bar but hide the actual boss from showing? Displaying the leveling progress is awesome but ruined by the bosses or boss effects shown in the distances. :(

Tried both BarAPI and BossBarAPI. (BossBarAPI also has a delay once the bar is all the way filled up when you leveled a skill and move on to the next level. BarAPI doesn't have this lag.)

**Comment by TuxCoding** [comment]
No it's not possible. The player has to see the boss. The author of BossBarAPI said that it's partly fixed in his version. 

What do you mean by the delay? How do you see this delay?
