### ISSUE TITLE
mcMMO messages to actionbar

### ISSUE THREAD

**Issue by RoboMWM** [games647/mcMMOExtras#4]
Is it possible to hook into McMMO messages and have its messages be displayed via the action bar (as proposed here: https://github.com/mcMMO-Dev/mcMMO/issues/2659)?

**Comment by TuxCoding** [comment]
I think I am going to create a pull request for the mcMMO repo. I guess it's better to implement it directly into mcMMO.

Sent from mobile.

**Comment by TuxCoding** [comment]
Sadly actionbar messages aren't included in the bukkit or spigot API. Since mcMMO doesn't want to use NMS, it would require an extra plugin for it. Is it okay if I use ProtocolLib for it?

**Comment by RoboMWM** [comment]
Sure, I already am trying plugins like actionannouncer which can use the [placeholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) or something

**Comment by TuxCoding** [comment]
Sorry for the delay. I was busy in the last days.

You can download it from the releases section.

**Comment by RoboMWM** [comment]
Ah, didn't know it was there or I just didn't pay attention, one of the two. Thanks, seems to be working well so far!
