### ISSUE TITLE
Old bossbar messages being displayed

### ISSUE THREAD

**Issue by RoboMWM** [games647/mcMMOExtras#5]
I'm using BossBarAPI, and my view-distance is set to 6.

It seems that when I move around in areas where I punched some mobs and leveled up unarmed, these messages remain there when I return to the area. Consequently, the bossbar message does not get removed. I am using the default config - with alwaysShow set to false.

I believe it happens when you move around an area attacking mobs - my guess is that the old messages are never removed when the message is updated (perhaps with a new bossbar entity). Only the "latest" messages get removed, but older ones that have not expired before a new "update" was sent are not.

**Comment by TuxCoding** [comment]
I'll look into it.
