### ISSUE TITLE
Suggestion: Toggable messages

### ISSUE THREAD

**Issue by DanSpedey** [games647/mcMMOExtras#6]
Hello, could you please add the option to enable/disable the different types of messages? e.g. Disable all level up messages.

Thanks

**Comment by TuxCoding** [comment]
This plugin is only for the level up progress. It displays the message as a boss bar. 

Maybe you mean [mcMMOAction](https://github.com/games647/mcMMOAction)?

**Comment by DanSpedey** [comment]
Oooops sorry, got confused between the two :p
