### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by madtomic** [games647/mcMMOExtras#7]
http://pastebin.com/0LkZ9Dcs

I don't know any BossBarMessageAPI

**Comment by madtomic** [comment]
I'm running 1.8.9 which McMMOExtras is a safe version to use. I just found out BarStyle is 1.9

**Comment by TuxCoding** [comment]
> I don't know any BossBarMessageAPI

It's BossBarAPI.

I introduced a couple of new features which are only available in 1.9.

**Comment by madtomic** [comment]
Thanks!
