### ISSUE TITLE
Doesn't work on 1.11.2

### ISSUE THREAD

**Issue by BiGUNMAN** [games647/mcMMOExtras#9]
Hi! I updated my server to 1.11.2 and mcMMO Extras just stopped working. It worked perfectly fine on 1.10.2

**Comment by TuxCoding** [comment]
Any errors?

**Comment by BiGUNMAN** [comment]
Nope, there are none :/

**Comment by TuxCoding** [comment]
Do you use any boss bar plugins? It works for me

**Comment by BiGUNMAN** [comment]
I do, but on 1.10 the two plugins worked perfectly together. Now mcMMO Extras doesn't work, but the other boss bar plugin does work (it sends boss bar messages every minute or so that last around 5 seconds).

I'll test and see if it's causing an issue by removing the other plugin.

EDIT: It's not the plugin, I removed it and restarted server and mcMMO Extras still doesn't work.

**Comment by TuxCoding** [comment]
>but the other boss bar plugin does work (it sends boss bar messages every minute or so that last around 
5 seconds)

I think that plugin overrides mcMMOExtras. What's the name of it?

**Comment by BiGUNMAN** [comment]
It doesn't, I removed it and it still didn't work. Regardless, its called BossMessenger, its Premium, and it worked together with mcMMO Extras on 1.10.2.

~~Does mcMMO extras rely on a certain config option being true in mcMMO though?~~ Tried resetting config, didn't do anything.

**Comment by TuxCoding** [comment]
>Does mcMMO extras rely on a certain config option being true in mcMMO though?
No it doesn't. 

Could you try it on a local test server with just mcMMO and mcMMOExtras? Sadly there is no easy way to get the currently associated bossbars of a player.

**Comment by BiGUNMAN** [comment]
Okay, that worked... Now I need to find the incompatibility.
Is there a reason where there are no error messages? I know its not Boss
Messenger since they worked together flawlessly, and when removing it it
didn't start working.
The other somewhat annoying thing is that those are the two only plugins
that should be using the Boss Bar.

**Comment by BiGUNMAN** [comment]
Found the issue, very stupid mistake by me. :) Sorry for taking your time!

**Comment by TuxCoding** [comment]
What was the cause? I'm very interested

**Comment by BiGUNMAN** [comment]
I had the mcmmoextras.expbar permission set to false. The weird thing is
even though its false, it said "expbar has been disabled/enabled", and not
"you do not have permission for this command", when executing /expbar.

**Comment by TuxCoding** [comment]
Thanks for the info
